phrases = {
    "To wave" : "at",
    "To connect" : "with",
    "To glare" : "at",
    "To smile" : "at",
    "To chat" : "with",
    "To shout" : "at", 
    "To whisper" : "to",
    "To write a letter" : "to",
    "To wink" : "at",
    "To shake hands" : "with",
    "To make an appointment" : "with",
    "To communicate" : "with",
    "To have a meeting" : "with",
    "To be out of touch" : "with",
    "To get hold" : "of",
    "To lose touch" : "with",
    "To lose contact" : "with",
    "To come into contact" : "with",
}